server:
  port: 8084
spring:
  application:
    name: suggestion-deal-mobile
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.100:3306/npc_platform_new?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=CTT&useSSL=false
    username: root
    password: cd@khd2018
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  resources:
    static-locations: ["classpath:/static/", "./static"]


# 微信服务号相关配置，科宏达测试号
service_app:
  #服务号 token
  token: fedf056b58c94c34acd2dcd9741b3038
  #服务号 appid
  appid: wx6e8e88c9d386bb9e
  #服务号secret
  appsecret: a88ed604f201eea0300bead4c7e3410a
  #待转办、待办理消息模板
  templetedId1: pWT8mGpwTVDhzQXZ9QtuNJtV-utao1b06KeAfofyPww
  #催办通知
  templetedId2: Wipr7FVwtdEfZ24QpSe0uVtOKZO_xTp6tcC0wXBqvcw
  #临期、超期通知
  templetedId3: BdHUUIyWFu543C2cz9fIA7UxY2cBpnHHV0Okjx175-A
  #办理完成通知代表
  templetedId4: QeMlbH90d70qBOAEoA3G8E7pkz6MY7nieQLJiFYV1zU
  #办结通知单位
  templetedId5: tc2gloKmzxOrUCa7QiKUVj6hyM_syxkZvEqLn0jbatc
  #意见建议回复提醒
  templetedId6: MpARgtznaTiKs5kqHL6d4QXnB44uc8zfE_WVWNCoOyw

  #跳转到小程序的页面
  pagepath: pages/index/index
  #登录公众号授权路径
  redirect_url: https://www.khdpro2.top/api/mobile/auth/access_token
  #小程序 appid  推送消息时需要
  miniapp_appid: wx10197c5d2f60df03

serverUrl:
  http://localhost:8080

account:
  suffix: cdkhd  #添加镇管理员生成的默认账号的后缀
  password: 123456 #默认密码
  mobile: 13551371473 #默认手机号
npc_base_info:
  area: 民权县
  user:
    name: admin
    mobile: 18428078565
  cdkhd:
    name: cdkhd
    mobile: 13551371473

