server:
  port: 8080
spring:
  application:
    name: npc-platform
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/npc_platform_new?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=CTT&useSSL=false
    username: root
    password: nian9695,,,
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  resources:
    static-locations: ["classpath:/static/", "./static"]

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 24MB

npc_base_info:
  area: 双流区
  user:
    name: admin
    mobile: 18940918501
  cdkhd:
    name: cdkhd
    mobile: 13551371473


service_app:
  app_id: 1
  app_secret: secret

code:
  #百度云安全认证key
  accessKeyId: a8d78d24102445d9a29557ad3f1fdd31
  #百度云安全认证secret
  AccessKeySecret: 0a74dae125f84ed592f1143731b21e22
  #百度云消息服务中心
  endPoint: http://sms.bj.baidubce.com
  #短信签名id
  invokeId: 0FaecrUS-V0hG-RqZG
  #短信模板id
  templateCode: smsTpl:35dbca99-ae04-47ac-8e79-51f567820bbb
  #验证码有效时间 单位：分钟
  timeout: 5 #分钟

account:
  suffix: cdkhd  #添加镇管理员生成的默认账号的后缀
  password: 123456 #默认密码
  mobile: 13333333333 #默认手机号

