server:
  port: 8083
spring:
  application:
    name: suggestion-deal
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.100:3306/npc_platform_new?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=CTT&useSSL=false
    username: root
    password: cd@khd2018
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  resources:
    static-locations: ["classpath:/static/", "./static"]


account:
  suffix: cdkhd  #添加镇管理员生成的默认账号的后缀
  password: 123456 #默认密码
  mobile: 13551371473 #默认手机号
npc_base_info:
  area: 民权县
  user:
    name: admin
    mobile: 18428078565
  cdkhd:
    name: cdkhd
    mobile: 13551371473

# 微信服务号相关配置，科宏达测试号
service_app:
  #服务号 token
  token: fedf056b58c94c34acd2dcd9741b3038
  #服务号 appid
  appid: wx6e8e88c9d386bb9e
  #服务号secret
  appsecret: a88ed604f201eea0300bead4c7e3410a
  #待审核提醒
  templetedId1: rtj7Pi26B75d1gMUnVwQFX-j4Iy8CJ5td9R18v2L0kc
  #审核通过通知
  templetedId2: vYFPBbNrds0bH2Wu3ZUA3Bf_AqkJlTdpghViVwatiT8
  #投诉建议通知
  templetedId3: S27PWGRD-Ze_OgLcyaqIgB4l57VBmX-p58s0MAAkWZ0
  #会议通知
  templetedId4: sjHook3xqJ8rc0ScQzQLDa0KY1C0r7DtXQ766EYUreI
  #意见建议回复提醒
  templetedId5: MpARgtznaTiKs5kqHL6d4QXnB44uc8zfE_WVWNCoOyw
  #跳转到小程序的页面
  pagepath: pages/index/index
  #登录公众号授权路径
  redirect_url: https://www.khdpro2.top/api/mobile/auth/access_token
  #小程序 appid  推送消息时需要
  miniapp_appid: wx10197c5d2f60df03

code:
  #百度云安全认证key
  accessKeyId: 36360a91e6f74df68e748768d1237e98
  #百度云安全认证secret
  AccessKeySecret: c204ecd345e947afab7a52d6cc9c0ec0
  #百度云消息服务中心
  endPoint: http://smsv3.bj.baidubce.com
  #短信签名id
  invokeId: sms-sign-gdnSpi95770
  #短信模板id
  templateCode: sms-tmpl-nQaeYW32805
  #验证码有效时间 单位：分钟
  timeout: 5 #分钟

serverUrl:
  http://localhost:8080
