server:
  port: 8083
spring:
  application:
    name: npc-member-house
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.12.112.156:3306/npc_platform?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=CTT&useSSL=false
    username: root
    password: cdkhd@2020
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  resources:
    static-locations: ["classpath:/static/", "./static"]

service_app:
  app_id: 1
  app_secret: secret
serverUrl:
  http://localhost:8080/api/manager/token/parseToken?token=

npc_base_info:
  area: 双流区
  user:
    name: admin
    mobile: 18940918501
  cdkhd:
    name: cdkhd
    mobile: 13551371473
