server:
  port: 8082
spring:
  application:
    name: npc-member-house
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.100:3306/npc_platform_new?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&serverTimezone=CTT&useSSL=false
    username: root
    password: cd@khd2018
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  resources:
    static-locations: ["classpath:/static/", "./static"]

# 微信服务号相关配置，科宏达测试号
service_app:
  #服务号 token
  token: fedf056b58c94c34acd2dcd9741b3038
  #服务号 appid
  appid: wx6f4bd0fb61bf0232
  #服务号secret
  appsecret: 7e828db5f6ff0e8dca6ba44198ada7c4
  #待审核提醒
  templetedId1: rtj7Pi26B75d1gMUnVwQFX-j4Iy8CJ5td9R18v2L0kc
  #审核通过通知
  templetedId2: vYFPBbNrds0bH2Wu3ZUA3Bf_AqkJlTdpghViVwatiT8
  #投诉建议通知
  templetedId3: S27PWGRD-Ze_OgLcyaqIgB4l57VBmX-p58s0MAAkWZ0
  #会议通知
  templetedId4: sjHook3xqJ8rc0ScQzQLDa0KY1C0r7DtXQ766EYUreI
  #意见建议回复提醒
  templetedId5: MpARgtznaTiKs5kqHL6d4QXnB44uc8zfE_WVWNCoOyw
  #跳转到小程序的页面
  pagepath: pages/index/index
  #登录公众号授权路径
  redirect_url: https://www.khdpro1.top/api/mobile/auth/access_token
  #小程序 appid  推送消息时需要
  miniapp_appid: wx6f6052b68ee8e7f0

serverUrl:
  http://localhost:8080

account:
  suffix: cdkhd  #添加镇管理员生成的默认账号的后缀
  password: 123456 #默认密码
  mobile: 13551371473 #默认手机号
npc_base_info:
  area: 双流区
  user:
    name: admin
    mobile: 18940918501
  cdkhd:
    name: cdkhd
    mobile: 13551371473
